# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - nightly
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: false
git:
  depth: 99999999

after_script:
  - julia -e 'using Pkg, SnpArrays; 'cd(joinpath(dirname(pathof(SnpArrays)), "..")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder()); Coveralls.submit(process_folder())'
  - julia -e 'using SnpArrays; include(joinpath(dirname(pathof(SnpArrays)), "..", "docs", "make.jl"))'
