site_name:        SnpArrays.jl
repo_url:         https://github.com/OpenMendel/SnpArrays.jl
site_description: Compressed storage for SNP data
site_author:      Hua Zhou

theme: material

extra:
  palette:
    primary: 'indigo'
    accent:  'blue'

extra_css:
  - assets/Documenter.css

markdown_extensions:
  - codehilite
  - extra
  - tables
  - fenced_code
  - mdx_math
  - admonition

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

docs_dir: 'build'

pages:
- Home: index.md
- Manual:
  - SnpArray: man/snparray.md
  - SnpData: man/snpdata.md
